services:
  web:
    profiles:
      - prod
    container_name: vidar_catalogue
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    profiles:
      - prod
    image: traefik:v3.2.3
    container_name: vidar_catalogue_traefik
    ports:
      - "8008:80"
      - "8081:8080"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    profiles:
      - prod
      - dev
    image: postgres:17-alpine
    container_name: vidar_catalogue_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
    postgres_data:
